/** Resource configs for in-app list + form (no Desk). */

export const SERVICE_REQUEST_STATUSES = [
	"Draft",
	"Open",
	"Under Validation",
	"Assigned",
	"Accepted",
	"Travel Started",
	"Reached Customer",
	"Inspection",
	"Waiting Customer",
	"Waiting Spare",
	"Repair In Progress",
	"Testing",
	"Customer Verification",
	"Completed",
	"Closed",
	"Cancelled",
];

/** Display list includes legacy aliases for filters on old rows */
export const SERVICE_REQUEST_STATUS_FILTER = [
	...SERVICE_REQUEST_STATUSES,
	"Reached Site",
	"Repair",
	"Customer Approval",
];

export const resources = {
	"service-requests": {
		route: "service-requests",
		listName: "Service Requests",
		detailName: "Service Request Detail",
		title: "Service Requests",
		singular: "Service Request",
		doctype: "Swift Service Request",
		fields: ["name", "subject", "customer", "status", "priority", "assigned_engineer", "modified"],
		columns: [
			{ key: "name", label: "ID", width: "10rem" },
			{ key: "subject", label: "Subject", width: "18rem" },
			{ key: "customer", label: "Customer", width: "14rem" },
			{ key: "status", label: "Status", width: "12rem" },
			{ key: "priority", label: "Priority", width: "8rem" },
			{ key: "assigned_engineer", label: "Engineer", width: "12rem" },
			{ key: "modified", label: "Last Modified", width: "9rem" },
		],
		statusField: "status",
		titleField: "subject",
		statusOptions: SERVICE_REQUEST_STATUSES,
		formFields: [
			{ section: "Basic", fieldname: "subject", label: "Subject", fieldtype: "Data", reqd: 1, col: "sm:col-span-2" },
			{ section: "Basic", fieldname: "status", label: "Status", fieldtype: "Select", options: SERVICE_REQUEST_STATUS_FILTER },
			{ section: "Basic", fieldname: "priority", label: "Priority", fieldtype: "Select", options: ["Low", "Medium", "High", "Urgent"] },
			{ section: "Basic", fieldname: "service_request_type", label: "Request Type", fieldtype: "Select", options: ["Breakdown", "Installation", "PM", "Calibration", "Demo", "Training", "Warranty", "AMC"] },
			{ section: "Customer", fieldname: "customer", label: "Customer", fieldtype: "Link", options: "Customer", reqd: 1 },
			{ section: "Customer", fieldname: "contact_person", label: "Contact", fieldtype: "Link", options: "Contact" },
			{ section: "Customer", fieldname: "mobile_no", label: "Mobile", fieldtype: "Data" },
			{ section: "Customer", fieldname: "email_id", label: "Email", fieldtype: "Data" },
			{ section: "Location", fieldname: "geo_latitude", label: "Site Latitude", fieldtype: "Float" },
			{ section: "Location", fieldname: "geo_longitude", label: "Site Longitude", fieldtype: "Float" },
			{ section: "Installed Product", fieldname: "installed_base", label: "Installed Product", fieldtype: "Link", options: "Installed Base" },
			{ section: "Installed Product", fieldname: "serial_no", label: "Serial No", fieldtype: "Link", options: "Serial No" },
			{ section: "Installed Product", fieldname: "item_code", label: "Item", fieldtype: "Link", options: "Item" },
			{ section: "Complaint", fieldname: "complaint_description", label: "Complaint", fieldtype: "Text", col: "sm:col-span-2 xl:col-span-3" },
			{ section: "Assignment", fieldname: "assigned_engineer", label: "Assigned Engineer", fieldtype: "Link", options: "User" },
			{ section: "Assignment", fieldname: "territory", label: "Territory", fieldtype: "Link", options: "Territory" },
		],
		createFields: [
			{ section: "Customer", fieldname: "customer", label: "Customer", fieldtype: "Link", options: "Customer", reqd: 1 },
			{ section: "Customer", fieldname: "territory", label: "Territory", fieldtype: "Link", options: "Territory" },
			{ section: "Installed Product", fieldname: "installed_base", label: "Installed Product", fieldtype: "Link", options: "Installed Base" },
			{ section: "Installed Product", fieldname: "serial_no", label: "Serial No", fieldtype: "Link", options: "Serial No" },
			{ section: "Complaint", fieldname: "subject", label: "Subject", fieldtype: "Data", reqd: 1, col: "sm:col-span-2" },
			{ section: "Complaint", fieldname: "priority", label: "Priority", fieldtype: "Select", default: "Medium", options: [{ label: "Low", value: "Low" }, { label: "Medium", value: "Medium" }, { label: "High", value: "High" }, { label: "Urgent", value: "Urgent" }] },
			{ section: "Complaint", fieldname: "complaint_type", label: "Type", fieldtype: "Select", default: "Breakdown", options: [{ label: "Breakdown", value: "Breakdown" }, { label: "Warranty", value: "Warranty" }, { label: "AMC / PM", value: "Preventive Maintenance" }, { label: "Installation", value: "Installation" }] },
			{ section: "Complaint", fieldname: "complaint_source", label: "Source", fieldtype: "Select", options: ["Phone", "Email", "WhatsApp", "Portal", "Dealer", "Mobile App"] },
			{ section: "Complaint", fieldname: "complaint_description", label: "Description", fieldtype: "Text", col: "sm:col-span-2" },
		],
		createMethod: "swiftservice.api.create_service_request",
		quickFilters: [
			{
				fieldname: "status",
				label: "Status",
				type: "Select",
				options: SERVICE_REQUEST_STATUS_FILTER.map((s) => ({ label: s, value: s })),
			},
			{ fieldname: "customer", label: "Customer", type: "Link", options: "Customer" },
			{ fieldname: "territory", label: "Territory", type: "Link", options: "Territory" },
			{ fieldname: "assigned_engineer", label: "Engineer", type: "Link", options: "User" },
			{ fieldname: "priority", label: "Priority", type: "Select", options: ["Low", "Medium", "High", "Urgent"].map((s) => ({ label: s, value: s })) },
		],
		process: "service-request",
		submittable: true,
	},
	"installed-base": {
		route: "installed-base",
		listName: "Installed Base",
		detailName: "Installed Base Detail",
		title: "Installed Base",
		singular: "Installed Base",
		doctype: "Installed Base",
		fields: ["name", "customer", "item_code", "serial_no", "warranty_end_date", "status", "modified"],
		columns: [
			{ key: "name", label: "ID", width: "10rem" },
			{ key: "customer", label: "Customer", width: "14rem" },
			{ key: "item_code", label: "Item", width: "12rem" },
			{ key: "serial_no", label: "Serial", width: "12rem" },
			{ key: "warranty_end_date", label: "Warranty End", width: "10rem" },
			{ key: "status", label: "Status", width: "10rem" },
		],
		statusField: "status",
		formFields: [
			{ section: "Customer & Product",  fieldname: "customer", label: "Customer", fieldtype: "Link", options: "Customer", reqd: 1 },
			{ section: "Product",  fieldname: "item_code", label: "Item", fieldtype: "Link", options: "Item", reqd: 1 },
			{ section: "Product", fieldname: "serial_no", label: "Serial No", fieldtype: "Link", options: "Serial No", filters: { item_code: "$item_code" } },
			{ section: "Product", fieldname: "model_no", label: "Model", fieldtype: "Data" },
			{ section: "Product", fieldname: "batch_no", label: "Batch", fieldtype: "Link", options: "Batch" },
			{ section: "Warranty & AMC",  fieldname: "installation_date", label: "Installation Date", fieldtype: "Date" },
			{ section: "Warranty & AMC",  fieldname: "warranty_start_date", label: "Warranty Start", fieldtype: "Date" },
			{ section: "Warranty & AMC",  fieldname: "warranty_end_date", label: "Warranty End", fieldtype: "Date" },
			{ section: "Warranty & AMC",  fieldname: "amc_end_date", label: "AMC End", fieldtype: "Date" },
			{ section: "Technical",  fieldname: "firmware_version", label: "Firmware", fieldtype: "Data" },
			{ section: "Technical",  fieldname: "software_version", label: "Software", fieldtype: "Data" },
			{ section: "Technical",  fieldname: "gps_location", label: "GPS", fieldtype: "Data" },
			{ section: "Status",  fieldname: "status", label: "Status", fieldtype: "Select", options: ["Active", "Inactive"] },
		],
		createFields: [
			{ section: "Customer & Product",  fieldname: "customer", label: "Customer", fieldtype: "Link", options: "Customer", reqd: 1 },
			{ section: "Product",  fieldname: "item_code", label: "Item", fieldtype: "Link", options: "Item", reqd: 1 },
			{ section: "Product", fieldname: "serial_no", label: "Serial No", fieldtype: "Link", options: "Serial No" },
			{ section: "Product", fieldname: "model_no", label: "Model", fieldtype: "Data" },
			{ section: "Status", fieldname: "status", label: "Status", fieldtype: "Select", default: "Active", options: [{ label: "Active", value: "Active" }, { label: "Inactive", value: "Inactive" }] },
		],
		quickFilters: [
			{ fieldname: "customer", label: "Customer", type: "Link", options: "Customer" },
			{ fieldname: "item_code", label: "Item", type: "Link", options: "Item" },
			{ fieldname: "serial_no", label: "Serial", type: "Link", options: "Serial No" },
		],
		submittable: true,
	},
	"engineer-assignments": {
		route: "engineer-assignments",
		listName: "Engineer Assignments",
		detailName: "Engineer Assignment Detail",
		title: "Engineer Assignments",
		singular: "Engineer Assignment",
		doctype: "Engineer Assignment",
		fields: [
			"name",
			"service_request",
			"customer",
			"primary_engineer",
			"status",
			"priority",
			"planned_visit",
			"modified",
		],
		columns: [
			{ key: "name", label: "Assignment", width: "10rem" },
			{ key: "service_request", label: "Service Request", width: "12rem" },
			{ key: "customer", label: "Customer", width: "12rem" },
			{ key: "primary_engineer", label: "Engineer", width: "12rem" },
			{ key: "status", label: "Status", width: "12rem" },
			{ key: "priority", label: "Priority", width: "8rem" },
			{ key: "planned_visit", label: "Planned", width: "9rem" },
		],
		statusField: "status",
		titleField: "name",
		statusOptions: [
			"Draft",
			"Pending Assignment",
			"Assigned",
			"Engineer Accepted",
			"Travel Started",
			"Reached Customer",
			"Visit Completed",
			"Assignment Closed",
			"Cancelled",
		],
		formFields: [
			{ section: "Links", fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
			{ section: "Links", fieldname: "customer", label: "Customer", fieldtype: "Link", options: "Customer" },
			{ section: "Links", fieldname: "installed_base", label: "Installed Product", fieldtype: "Link", options: "Installed Base" },
			{ section: "Engineer", fieldname: "primary_engineer", label: "Primary Engineer", fieldtype: "Link", options: "User", reqd: 1 },
			{ section: "Engineer", fieldname: "secondary_engineer", label: "Secondary Engineer", fieldtype: "Link", options: "User" },
			{ section: "Assignment", fieldname: "status", label: "Status", fieldtype: "Select", options: ["Draft", "Pending Assignment", "Assigned", "Engineer Accepted", "Travel Started", "Reached Customer", "Visit Completed", "Assignment Closed", "Cancelled"] },
			{ section: "Assignment", fieldname: "priority", label: "Priority", fieldtype: "Select", options: ["Low", "Medium", "High", "Urgent"] },
			{ section: "Assignment", fieldname: "planned_visit", label: "Planned Visit", fieldtype: "Date" },
			{ section: "Assignment", fieldname: "sla_deadline", label: "SLA Deadline", fieldtype: "Datetime" },
			{ section: "Assignment", fieldname: "closure_remarks", label: "Remarks", fieldtype: "Small Text", col: "sm:col-span-2" },
		],
		createFields: [
			{ section: "Links", fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
			{ section: "Engineer", fieldname: "primary_engineer", label: "Primary Engineer", fieldtype: "Link", options: "User", reqd: 1 },
			{ section: "Engineer", fieldname: "secondary_engineer", label: "Secondary", fieldtype: "Link", options: "User" },
			{ section: "Assignment", fieldname: "planned_visit", label: "Planned Visit", fieldtype: "Date" },
			{ section: "Assignment", fieldname: "priority", label: "Priority", fieldtype: "Select", default: "Medium", options: ["Low", "Medium", "High", "Urgent"].map((s) => ({ label: s, value: s })) },
		],
		quickFilters: [
			{
				fieldname: "status",
				label: "Status",
				type: "Select",
				options: [
					"Pending Assignment",
					"Assigned",
					"Engineer Accepted",
					"Travel Started",
					"Reached Customer",
					"Visit Completed",
					"Assignment Closed",
				].map((s) => ({ label: s, value: s })),
			},
			{ fieldname: "primary_engineer", label: "Engineer", type: "Link", options: "User" },
			{ fieldname: "service_request", label: "Service Request", type: "Link", options: "Swift Service Request" },
			{ fieldname: "priority", label: "Priority", type: "Select", options: ["Low", "Medium", "High", "Urgent"].map((s) => ({ label: s, value: s })) },
		],
		process: "engineer-assignment",
		submittable: true,
	},
	"engineer-visits": {
		route: "engineer-visits",
		listName: "Service Visits",
		detailName: "Service Visit Detail",
		title: "Service Visits",
		singular: "Service Visit",
		doctype: "Engineer Visit",
		fields: ["name", "service_request", "engineer", "visit_date", "visit_type", "status", "diagnosis_result", "modified"],
		columns: [
			{ key: "name", label: "Visit", width: "10rem" },
			{ key: "service_request", label: "Service Request", width: "14rem" },
			{ key: "engineer", label: "Engineer", width: "12rem" },
			{ key: "visit_date", label: "Date", width: "8rem" },
			{ key: "visit_type", label: "Type", width: "8rem" },
			{ key: "status", label: "Status", width: "10rem" },
			{ key: "diagnosis_result", label: "Outcome", width: "10rem" },
		],
		statusField: "status",
		statusOptions: [
			"Draft",
			"Scheduled",
			"Travel Started",
			"Reached Site",
			"GPS Check-In",
			"Inspection",
			"Diagnosis",
			"Repair",
			"Testing",
			"Customer Verification",
			"GPS Check-Out",
			"Completed",
			"Cancelled",
			"Planned",
			"Confirmed",
			"Travel",
			"In Progress",
		],
		formFields: [
			{ section: "Links", fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
			{ section: "Links", fieldname: "engineer_assignment", label: "Assignment", fieldtype: "Link", options: "Engineer Assignment" },
			{ section: "Visit", fieldname: "engineer", label: "Engineer", fieldtype: "Link", options: "User", reqd: 1 },
			{ section: "Visit", fieldname: "status", label: "Status", fieldtype: "Select", options: ["Draft", "Scheduled", "Travel Started", "Reached Site", "In Progress", "Completed", "Cancelled"] },
			{ section: "Visit", fieldname: "planned_date", label: "Planned Date", fieldtype: "Date" },
			{ section: "GPS", fieldname: "check_in_time", label: "Check-in Time", fieldtype: "Datetime", read_only: 1 },
			{ section: "GPS", fieldname: "check_in_address", label: "Check-in Address", fieldtype: "Small Text", read_only: 1, col: "sm:col-span-2" },
			{ section: "GPS", fieldname: "check_out_time", label: "Check-out Time", fieldtype: "Datetime", read_only: 1 },
			{ section: "GPS", fieldname: "check_out_address", label: "Check-out Address", fieldtype: "Small Text", read_only: 1, col: "sm:col-span-2" },
			{ section: "GPS", fieldname: "distance_from_customer", label: "Distance (m)", fieldtype: "Float", read_only: 1 },
			{ section: "Visit", fieldname: "work_done", label: "Work Done", fieldtype: "Text", col: "sm:col-span-2" },
		],
		createFields: [
			{ section: "Links", fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
			{ section: "Assignment", fieldname: "engineer", label: "Engineer", fieldtype: "Link", options: "User", reqd: 1 },
			{ section: "Visit", fieldname: "visit_date", label: "Visit Date", fieldtype: "Date" },
			{ section: "Visit", fieldname: "visit_type", label: "Visit Type", fieldtype: "Select", options: ["Breakdown", "Installation", "PM", "Calibration", "AMC", "Follow-up", "Verification", "Training"], default: "Breakdown" },
			{ section: "Visit", fieldname: "naming_series", label: "Series", fieldtype: "Select", options: ["SV-.YYYY.-.#####", "EV-.YYYY.-.#####"], default: "SV-.YYYY.-.#####" },
		],
		quickFilters: [
			{ fieldname: "status", label: "Status", type: "Select", options: ["Scheduled", "Travel Started", "GPS Check-In", "Diagnosis", "Repair", "Completed"].map((s) => ({ label: s, value: s })) },
			{ fieldname: "engineer", label: "Engineer", type: "Data" },
			{ fieldname: "visit_type", label: "Type", type: "Select", options: ["Breakdown", "PM", "AMC", "Installation"].map((s) => ({ label: s, value: s })) },
		],
		process: "visit",
		submittable: true,
	},
	"diagnoses": {
		route: "diagnoses",
		listName: "Diagnosis / RCA",
		detailName: "Diagnosis Detail",
		title: "Diagnosis & RCA",
		singular: "Diagnosis",
		doctype: "Failure Analysis",
		fields: [
			"name",
			"service_request",
			"engineer_visit",
			"failure_category",
			"root_cause_category",
			"diagnosis_result",
			"status",
			"severity",
			"is_repeat_failure",
			"modified",
		],
		columns: [
			{ key: "name", label: "Diagnosis", width: "10rem" },
			{ key: "service_request", label: "Service Request", width: "12rem" },
			{ key: "failure_category", label: "Failure", width: "9rem" },
			{ key: "root_cause_category", label: "Root Cause", width: "11rem" },
			{ key: "diagnosis_result", label: "Outcome", width: "10rem" },
			{ key: "status", label: "Status", width: "10rem" },
			{ key: "severity", label: "Severity", width: "8rem" },
		],
		statusField: "status",
		statusOptions: [
			"Draft",
			"Inspection",
			"Analysis",
			"Root Cause Identified",
			"Corrective Action",
			"Verification",
			"Approved",
			"Closed",
			"Cancelled",
		],
		formFields: [
			{ section: "Links", fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
			{ section: "Links", fieldname: "engineer_visit", label: "Visit", fieldtype: "Link", options: "Engineer Visit" },
			{ section: "Diagnosis", fieldname: "status", label: "Status", fieldtype: "Select", options: ["Draft", "In Progress", "Completed"] },
			{ section: "Diagnosis", fieldname: "fault_code", label: "Fault Code", fieldtype: "Data" },
			{ section: "Diagnosis", fieldname: "root_cause", label: "Root Cause", fieldtype: "Text", col: "sm:col-span-2" },
			{ section: "Diagnosis", fieldname: "recommended_action", label: "Recommended Action", fieldtype: "Text", col: "sm:col-span-2" },
		],
		createFields: [
			{ section: "Linking", fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request" },
			{ section: "Linking", fieldname: "engineer_visit", label: "Service Visit", fieldtype: "Link", options: "Engineer Visit" },
			{ section: "Basic", fieldname: "source", label: "Source", fieldtype: "Select", options: ["Service Visit", "Workshop Repair", "Preventive Maintenance", "Installation", "Calibration", "Manufacturing Failure", "Quality Complaint", "Manual"], default: "Manual" },
			{ section: "Basic", fieldname: "naming_series", label: "Series", fieldtype: "Select", options: ["DX-.YYYY.-.#####", "FA-.YYYY.-.#####"], default: "DX-.YYYY.-.#####" },
		],
		quickFilters: [
			{ fieldname: "status", label: "Status", type: "Select", options: ["Draft", "Analysis", "Root Cause Identified", "Approved", "Closed"].map((s) => ({ label: s, value: s })) },
			{ fieldname: "root_cause_category", label: "Root Cause", type: "Select", options: ["Manufacturing Defect", "Design Defect", "Supplier Issue", "Wear & Tear"].map((s) => ({ label: s, value: s })) },
			{ fieldname: "severity", label: "Severity", type: "Select", options: ["Low", "Medium", "High", "Critical"].map((s) => ({ label: s, value: s })) },
		],
		process: "diagnosis",
		submittable: true,
	},
	"spare-requests": {
		route: "spare-requests",
		listName: "Spare Requests",
		detailName: "Spare Request Detail",
		title: "Spare Requests",
		singular: "Spare Request",
		doctype: "Spare Request",
		fields: [
			"name",
			"service_request",
			"item_code",
			"qty",
			"priority",
			"request_type",
			"stock_status",
			"status",
			"modified",
		],
		columns: [
			{ key: "name", label: "Request", width: "10rem" },
			{ key: "service_request", label: "Service Request", width: "12rem" },
			{ key: "item_code", label: "Item", width: "10rem" },
			{ key: "qty", label: "Qty", width: "5rem" },
			{ key: "priority", label: "Priority", width: "7rem" },
			{ key: "stock_status", label: "Stock", width: "8rem" },
			{ key: "status", label: "Status", width: "10rem" },
		],
		statusField: "status",
		statusOptions: [
			"Draft",
			"Pending Approval",
			"Approved",
			"Stock Check",
			"Reserved",
			"Issued",
			"In Transit",
			"Received by Engineer",
			"Consumed",
			"Completed",
			"Closed",
			"Cancelled",
			"Pending Purchase",
		],
		formFields: [
			{ section: "Links", fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
			{ section: "Request", fieldname: "status", label: "Status", fieldtype: "Select", options: ["Draft", "Pending Approval", "Approved", "Reserved", "Issued", "Consumed", "Closed", "Cancelled"] },
			{ section: "Request", fieldname: "priority", label: "Priority", fieldtype: "Select", options: ["Low", "Medium", "High", "Urgent"] },
			{ section: "Request", fieldname: "requested_by", label: "Requested By", fieldtype: "Link", options: "User" },
			{ section: "Stock", fieldname: "warehouse", label: "Warehouse (Issue From)", fieldtype: "Link", options: "Warehouse" },
			{ section: "Stock", fieldname: "item_code", label: "Item", fieldtype: "Link", options: "Item" },
			{ section: "Stock", fieldname: "qty", label: "Qty", fieldtype: "Float" },
			{ section: "Stock", fieldname: "stock_entry", label: "Stock Entry (Issue)", fieldtype: "Link", options: "Stock Entry" },
			{ section: "Stock", fieldname: "stock_status", label: "Stock Status", fieldtype: "Data" },
			{ section: "Stock", fieldname: "purchase_request", label: "Material Request", fieldtype: "Data" },
			{ section: "Request", fieldname: "remarks", label: "Remarks", fieldtype: "Small Text", col: "sm:col-span-2" },
		],
		createFields: [
			{ section: "References", fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
			{ section: "Parts", fieldname: "item_code", label: "Item", fieldtype: "Link", options: "Item", reqd: 1 },
			{ section: "Parts", fieldname: "qty", label: "Qty", fieldtype: "Float", default: 1 },
			{ section: "Parts", fieldname: "warehouse", label: "Warehouse", fieldtype: "Link", options: "Warehouse" },
			{ section: "Basic", fieldname: "priority", label: "Priority", fieldtype: "Select", options: ["Low", "Medium", "High", "Urgent", "Emergency"], default: "Medium" },
			{ section: "Basic", fieldname: "request_type", label: "Request Type", fieldtype: "Select", options: ["Emergency Breakdown", "Scheduled Maintenance", "Preventive Maintenance", "Installation", "Calibration", "Replacement", "Warranty", "Chargeable", "Internal Consumption"], default: "Emergency Breakdown" },
			{ section: "Basic", fieldname: "naming_series", label: "Series", fieldtype: "Select", options: ["SPR-.YYYY.-.#####"], default: "SPR-.YYYY.-.#####" },
		],
		createMethod: "swiftservice.api.create_spare_request",
		quickFilters: [
			{ fieldname: "status", label: "Status", type: "Select", options: ["Draft", "Pending Approval", "Approved", "Reserved", "Issued", "Pending Purchase", "Consumed"].map((s) => ({ label: s, value: s })) },
			{ fieldname: "priority", label: "Priority", type: "Select", options: ["Medium", "High", "Urgent", "Emergency"].map((s) => ({ label: s, value: s })) },
		],
		process: "spare",
		submittable: true,
	},
	rma: {
		route: "rma",
		listName: "RMA",
		detailName: "RMA Detail",
		title: "RMA Cases",
		singular: "RMA Case",
		doctype: "RMA Case",
		fields: ["name", "service_request", "pickup_date", "repair_status", "dispatch_date", "modified"],
		columns: [
			{ key: "name", label: "RMA", width: "10rem" },
			{ key: "service_request", label: "Service Request", width: "14rem" },
			{ key: "pickup_date", label: "Pickup", width: "10rem" },
			{ key: "repair_status", label: "Status", width: "10rem" },
			{ key: "dispatch_date", label: "Dispatch", width: "10rem" },
		],
		statusField: "repair_status",
		statusOptions: ["Initiated", "Picked Up", "Received", "QC", "Diagnosis", "Repair", "Testing", "Dispatched"],
		formFields: [
			{ section: "Links", fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
			{ section: "RMA", fieldname: "status", label: "Status", fieldtype: "Select", options: ["Draft", "Open", "In Factory", "Repaired", "Closed", "Cancelled"] },
			{ section: "RMA", fieldname: "serial_no", label: "Serial No", fieldtype: "Link", options: "Serial No" },
			{ section: "RMA", fieldname: "reason", label: "Reason", fieldtype: "Text", col: "sm:col-span-2" },
		],
		createFields: [
			{ section: "Links",  fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
		],
		createMethod: "swiftservice.api.create_rma_case",
		quickFilters: [{ fieldname: "repair_status", label: "Status", type: "Data" }],
		process: "rma",
	},
	replacements: {
		route: "replacements",
		listName: "Replacements",
		detailName: "Replacement Detail",
		title: "Replacements",
		singular: "Replacement Case",
		doctype: "Replacement Case",
		fields: ["name", "service_request", "approval_status", "new_serial_no", "old_serial_no", "modified"],
		columns: [
			{ key: "name", label: "ID", width: "10rem" },
			{ key: "service_request", label: "Service Request", width: "14rem" },
			{ key: "approval_status", label: "Approval", width: "10rem" },
			{ key: "new_serial_no", label: "New Serial", width: "12rem" },
			{ key: "old_serial_no", label: "Old Serial", width: "12rem" },
		],
		statusField: "approval_status",
		formFields: [
			{ section: "Links",  fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
			{ section: "Status",  fieldname: "approval_status", label: "Approval", fieldtype: "Select", options: ["Pending", "Technical Approved", "Approved", "Rejected", "Completed"] },
			{ section: "Serials", fieldname: "old_serial_no", label: "Old Serial", fieldtype: "Link", options: "Serial No" },
			{ section: "Serials", fieldname: "new_serial_no", label: "New Serial", fieldtype: "Link", options: "Serial No" },
			{ section: "Logistics",  fieldname: "dispatch_date", label: "Dispatch", fieldtype: "Date" },
		],
		createFields: [
			{ section: "Links",  fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
		],
		createMethod: "swiftservice.api.create_replacement_case",
		quickFilters: [{ fieldname: "approval_status", label: "Approval", type: "Data" }],
		process: "replacement",
	},
	"pm-visits": {
		route: "pm-visits",
		listName: "PM Visits",
		detailName: "PM Visit Detail",
		title: "PM Visits",
		singular: "PM Visit",
		doctype: "Preventive Maintenance Visit",
		fields: ["name", "installed_base", "customer", "scheduled_date", "engineer", "status", "modified"],
		columns: [
			{ key: "name", label: "Visit", width: "10rem" },
			{ key: "installed_base", label: "Installed Base", width: "12rem" },
			{ key: "customer", label: "Customer", width: "14rem" },
			{ key: "scheduled_date", label: "Scheduled", width: "10rem" },
			{ key: "engineer", label: "Engineer", width: "12rem" },
			{ key: "status", label: "Status", width: "10rem" },
		],
		statusField: "status",
		formFields: [
			{ section: "Customer & Product",  fieldname: "installed_base", label: "Installed Base", fieldtype: "Link", options: "Installed Base", reqd: 1 },
			{ section: "Customer & Product",  fieldname: "customer", label: "Customer", fieldtype: "Link", options: "Customer" },
			{ section: "Visit",  fieldname: "scheduled_date", label: "Scheduled", fieldtype: "Date" },
			{ section: "Assignment",  fieldname: "engineer", label: "Engineer", fieldtype: "Link", options: "User" },
			{ section: "Status",  fieldname: "status", label: "Status", fieldtype: "Select", options: ["Planned", "Assigned", "Completed", "Cancelled"] },
			{ section: "Schedule",  fieldname: "next_visit_date", label: "Next Visit", fieldtype: "Date" },
		],
		createFields: [
			{ section: "Customer & Product",  fieldname: "installed_base", label: "Installed Base", fieldtype: "Link", options: "Installed Base", reqd: 1 },
			{ section: "Visit",  fieldname: "scheduled_date", label: "Scheduled Date", fieldtype: "Date", reqd: 1 },
			{ section: "Assignment",  fieldname: "engineer", label: "Engineer", fieldtype: "Link", options: "User" },
		],
		createMethod: "swiftservice.api.create_pm_visit",
		quickFilters: [{ fieldname: "status", label: "Status", type: "Data" }],
	},
	"amc-contracts": {
		route: "amc-contracts",
		listName: "AMC Contracts",
		detailName: "AMC Contract Detail",
		title: "AMC Contracts",
		singular: "AMC Contract",
		doctype: "AMC Contract",
		fields: ["name", "customer", "installed_base", "start_date", "end_date", "remaining_visits", "status", "modified"],
		columns: [
			{ key: "name", label: "ID", width: "10rem" },
			{ key: "customer", label: "Customer", width: "14rem" },
			{ key: "installed_base", label: "Installed Base", width: "12rem" },
			{ key: "end_date", label: "End", width: "10rem" },
			{ key: "remaining_visits", label: "Visits Left", width: "8rem" },
			{ key: "status", label: "Status", width: "10rem" },
		],
		statusField: "status",
		formFields: [
			{ section: "Customer & Product",  fieldname: "customer", label: "Customer", fieldtype: "Link", options: "Customer", reqd: 1 },
			{ section: "Customer & Product",  fieldname: "installed_base", label: "Installed Base", fieldtype: "Link", options: "Installed Base" },
			{ section: "Contract",  fieldname: "start_date", label: "Start", fieldtype: "Date" },
			{ section: "Contract",  fieldname: "end_date", label: "End", fieldtype: "Date" },
			{ section: "Contract",  fieldname: "free_visits", label: "Free Visits", fieldtype: "Float" },
			{ section: "Contract",  fieldname: "paid_visits", label: "Paid Visits", fieldtype: "Float" },
			{ section: "Contract",  fieldname: "remaining_visits", label: "Remaining", fieldtype: "Float" },
			{ section: "Status",  fieldname: "status", label: "Status", fieldtype: "Select", options: ["Draft", "Active", "Expired", "Cancelled"] },
		],
		createFields: [
			{ section: "Customer & Product",  fieldname: "customer", label: "Customer", fieldtype: "Link", options: "Customer", reqd: 1 },
			{ section: "Customer & Product",  fieldname: "installed_base", label: "Installed Base", fieldtype: "Link", options: "Installed Base" },
			{ section: "Contract",  fieldname: "start_date", label: "Start", fieldtype: "Date" },
			{ section: "Contract",  fieldname: "end_date", label: "End", fieldtype: "Date" },
			{ section: "Contract",  fieldname: "free_visits", label: "Free Visits", fieldtype: "Float", default: 4 },
			{ section: "Status",  fieldname: "status", label: "Status", fieldtype: "Select", default: "Active", options: [{ label: "Active", value: "Active" }, { label: "Draft", value: "Draft" }] },
		],
		quickFilters: [{ fieldname: "status", label: "Status", type: "Data" }],
	},
	calibrations: {
		route: "calibrations",
		listName: "Calibrations",
		detailName: "Calibration Detail",
		title: "Calibration Certificates",
		singular: "Calibration Certificate",
		doctype: "Calibration Certificate",
		fields: ["name", "installed_base", "certificate_no", "issue_date", "due_date", "result", "status", "modified"],
		columns: [
			{ key: "name", label: "ID", width: "10rem" },
			{ key: "installed_base", label: "Installed Base", width: "12rem" },
			{ key: "certificate_no", label: "Certificate", width: "12rem" },
			{ key: "due_date", label: "Due", width: "10rem" },
			{ key: "result", label: "Result", width: "10rem" },
			{ key: "status", label: "Status", width: "10rem" },
		],
		statusField: "status",
		formFields: [
			{ section: "Customer & Product",  fieldname: "installed_base", label: "Installed Base", fieldtype: "Link", options: "Installed Base", reqd: 1 },
			{ section: "Certificate",  fieldname: "certificate_no", label: "Certificate No", fieldtype: "Data" },
			{ section: "Certificate",  fieldname: "nabl_applicable", label: "NABL", fieldtype: "Check" },
			{ section: "Certificate",  fieldname: "standard_used", label: "Standard", fieldtype: "Data" },
			{ section: "Certificate",  fieldname: "result", label: "Result", fieldtype: "Select", options: ["Pass", "Fail", "Conditional"] },
			{ section: "Certificate",  fieldname: "issue_date", label: "Issue Date", fieldtype: "Date" },
			{ section: "Certificate",  fieldname: "due_date", label: "Due Date", fieldtype: "Date" },
			{ section: "Status",  fieldname: "status", label: "Status", fieldtype: "Select", options: ["Draft", "Issued", "Expired"] },
		],
		createFields: [
			{ section: "Customer & Product",  fieldname: "installed_base", label: "Installed Base", fieldtype: "Link", options: "Installed Base", reqd: 1 },
			{ section: "Certificate",  fieldname: "certificate_no", label: "Certificate No", fieldtype: "Data", reqd: 1 },
			{ section: "Certificate",  fieldname: "result", label: "Result", fieldtype: "Select", options: [{ label: "Pass", value: "Pass" }, { label: "Fail", value: "Fail" }] },
			{ section: "Certificate",  fieldname: "due_date", label: "Due Date", fieldtype: "Date" },
		],
		quickFilters: [{ fieldname: "status", label: "Status", type: "Data" }],
	},
	"service-reports": {
		route: "service-reports",
		listName: "Service Reports",
		detailName: "Service Report Detail",
		title: "Service Reports",
		singular: "Service Report",
		doctype: "Service Report",
		fields: [
			"name",
			"service_request",
			"engineer_visit",
			"report_date",
			"status",
			"revision",
			"primary_engineer",
			"modified",
		],
		columns: [
			{ key: "name", label: "Report", width: "10rem" },
			{ key: "service_request", label: "Service Request", width: "12rem" },
			{ key: "engineer_visit", label: "Visit", width: "10rem" },
			{ key: "report_date", label: "Date", width: "8rem" },
			{ key: "revision", label: "Rev", width: "4rem" },
			{ key: "status", label: "Status", width: "11rem" },
		],
		statusField: "status",
		statusOptions: [
			"Draft",
			"Generated",
			"Engineer Review",
			"Customer Review",
			"Customer Signed",
			"Manager Verification",
			"Billing Ready",
			"Submitted",
			"Cancelled",
		],
		formFields: [
			{ section: "Links", fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
			{ section: "Report", fieldname: "status", label: "Status", fieldtype: "Select", options: ["Draft", "Submitted", "Approved", "Cancelled"] },
			{ section: "Report", fieldname: "engineer", label: "Engineer", fieldtype: "Link", options: "User" },
			{ section: "Report", fieldname: "work_summary", label: "Work Summary", fieldtype: "Text Editor", col: "sm:col-span-2 xl:col-span-3" },
			{ section: "Report", fieldname: "customer_remarks", label: "Customer Remarks", fieldtype: "Small Text", col: "sm:col-span-2" },
		],
		createFields: [],
		creatable: false,
		quickFilters: [
			{ fieldname: "status", label: "Status", type: "Select", options: ["Generated", "Customer Review", "Customer Signed", "Billing Ready"].map((s) => ({ label: s, value: s })) },
		],
		process: "service-report",
		submittable: true,
	},
	feedback: {
		route: "feedback",
		listName: "Feedback",
		detailName: "Feedback Detail",
		title: "Customer Feedback",
		singular: "Feedback",
		doctype: "Customer Feedback",
		fields: [
			"name",
			"service_request",
			"customer",
			"csat_rating",
			"nps_score",
			"nps_category",
			"status",
			"engineer",
			"modified",
		],
		columns: [
			{ key: "name", label: "Feedback", width: "10rem" },
			{ key: "service_request", label: "Service Request", width: "12rem" },
			{ key: "csat_rating", label: "CSAT", width: "5rem" },
			{ key: "nps_score", label: "NPS", width: "5rem" },
			{ key: "nps_category", label: "Category", width: "8rem" },
			{ key: "status", label: "Status", width: "11rem" },
		],
		statusField: "status",
		statusOptions: [
			"Draft",
			"Feedback Requested",
			"Customer Responded",
			"Reviewed",
			"Escalation",
			"Closed",
			"Cancelled",
		],
		formFields: [
			{ section: "Links", fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
			{ section: "Feedback", fieldname: "status", label: "Status", fieldtype: "Select", options: ["Draft", "Feedback Requested", "Customer Responded", "Reviewed", "Closed", "Cancelled"] },
			{ section: "Feedback", fieldname: "customer", label: "Customer", fieldtype: "Link", options: "Customer" },
			{ section: "Feedback", fieldname: "csat_rating", label: "CSAT (1-5)", fieldtype: "Select", options: ["", "1", "2", "3", "4", "5"] },
			{ section: "Feedback", fieldname: "nps_score", label: "NPS (0-10)", fieldtype: "Int" },
			{ section: "Comments", fieldname: "positive_feedback", label: "Positive Feedback", fieldtype: "Small Text", col: "sm:col-span-2" },
			{ section: "Comments", fieldname: "complaint_text", label: "Complaint", fieldtype: "Small Text", col: "sm:col-span-2" },
		],
		createFields: [
			{ section: "References", fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
			{ section: "References", fieldname: "service_report", label: "Service Report", fieldtype: "Link", options: "Service Report" },
		],
		createMethod: "swiftservice.api.create_feedback",
		quickFilters: [
			{ fieldname: "status", label: "Status", type: "Select", options: ["Feedback Requested", "Customer Responded", "Escalation", "Closed"].map((s) => ({ label: s, value: s })) },
			{ fieldname: "nps_category", label: "NPS", type: "Select", options: ["Promoter", "Passive", "Detractor"].map((s) => ({ label: s, value: s })) },
		],
		process: "feedback",
		submittable: true,
	},
	"service-closures": {
		route: "service-closures",
		listName: "Service Closures",
		detailName: "Service Closure Detail",
		title: "Service Closure",
		singular: "Service Closure",
		doctype: "Service Closure",
		fields: [
			"name",
			"service_request",
			"customer",
			"status",
			"closure_reason",
			"validation_passed",
			"closed_on",
			"modified",
		],
		columns: [
			{ key: "name", label: "Closure", width: "10rem" },
			{ key: "service_request", label: "Service Request", width: "12rem" },
			{ key: "customer", label: "Customer", width: "12rem" },
			{ key: "validation_passed", label: "Valid", width: "5rem" },
			{ key: "status", label: "Status", width: "11rem" },
			{ key: "closure_reason", label: "Reason", width: "12rem" },
		],
		statusField: "status",
		statusOptions: [
			"Draft",
			"Validation",
			"Validation Failed",
			"Manager Review",
			"Approved",
			"Closed",
			"Archived",
			"Reopen Requested",
			"Reopened",
			"Cancelled",
		],
		formFields: [
			{ section: "Links", fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
			{ section: "Closure", fieldname: "status", label: "Status", fieldtype: "Select", options: ["Draft", "Closed", "Cancelled"] },
			{ section: "Closure", fieldname: "closure_date", label: "Closure Date", fieldtype: "Date" },
			{ section: "Closure", fieldname: "notes", label: "Notes", fieldtype: "Text", col: "sm:col-span-2" },
		],
		createFields: [
			{ section: "References", fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
		],
		createMethod: "swiftservice.api.create_service_closure",
		creatable: false,
		quickFilters: [
			{ fieldname: "status", label: "Status", type: "Select", options: ["Validation Failed", "Manager Review", "Approved", "Closed", "Reopen Requested"].map((s) => ({ label: s, value: s })) },
		],
		process: "closure",
		submittable: true,
	},
	billing: {
		route: "billing",
		listName: "Billing",
		detailName: "Billing Detail",
		title: "Billing & Settlement",
		singular: "Service Billing",
		doctype: "Service Billing",
		fields: [
			"name",
			"service_request",
			"commercial_type",
			"status",
			"grand_total",
			"invoice_amount",
			"sales_invoice",
			"modified",
		],
		columns: [
			{ key: "name", label: "Billing", width: "10rem" },
			{ key: "service_request", label: "Service Request", width: "12rem" },
			{ key: "commercial_type", label: "Type", width: "9rem" },
			{ key: "invoice_amount", label: "Invoice Amt", width: "9rem" },
			{ key: "status", label: "Status", width: "11rem" },
		],
		statusField: "status",
		statusOptions: [
			"Draft",
			"Commercial Review",
			"Customer Approval",
			"Approved",
			"Invoice Generated",
			"Payment Pending",
			"Payment Received",
			"Warranty Settlement",
			"Closed",
			"Cancelled",
			"Disputed",
		],
		formFields: [
			{ section: "Links", fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
			{ section: "Billing", fieldname: "customer", label: "Customer", fieldtype: "Link", options: "Customer" },
			{ section: "Billing", fieldname: "status", label: "Status", fieldtype: "Select", options: ["Draft", "Commercial Review", "Approved", "Invoice Generated", "Payment Pending", "Payment Received", "Closed", "Cancelled"] },
			{ section: "Billing", fieldname: "commercial_type", label: "Commercial Type", fieldtype: "Data" },
			{ section: "Amounts", fieldname: "grand_total", label: "Grand Total", fieldtype: "Currency" },
			{ section: "Amounts", fieldname: "invoice_amount", label: "Invoice Amount", fieldtype: "Currency" },
			{ section: "Amounts", fieldname: "outstanding_amount", label: "Outstanding", fieldtype: "Currency" },
			{ section: "ERPNext Accounts", fieldname: "sales_invoice", label: "Sales Invoice", fieldtype: "Link", options: "Sales Invoice" },
			{ section: "ERPNext Accounts", fieldname: "company", label: "Company", fieldtype: "Link", options: "Company" },
			{ section: "ERPNext Accounts", fieldname: "taxes_and_charges", label: "Sales Taxes Template", fieldtype: "Link", options: "Sales Taxes and Charges Template" },
			{ section: "Billing", fieldname: "notes", label: "Notes", fieldtype: "Text", col: "sm:col-span-2" },
		],
		createFields: [
			{ section: "References", fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
			{ section: "References", fieldname: "service_report", label: "Service Report", fieldtype: "Link", options: "Service Report" },
		],
		createMethod: "swiftservice.api.create_service_billing",
		quickFilters: [
			{ fieldname: "status", label: "Status", type: "Select", options: ["Commercial Review", "Customer Approval", "Payment Pending", "Warranty Settlement"].map((s) => ({ label: s, value: s })) },
			{ fieldname: "commercial_type", label: "Type", type: "Select", options: ["Warranty", "AMC", "Paid Service", "Mixed"].map((s) => ({ label: s, value: s })) },
		],
		process: "billing",
		submittable: true,
	},
	estimates: {
		route: "estimates",
		listName: "Estimates",
		detailName: "Estimate Detail",
		title: "Service Estimates",
		singular: "Service Estimate",
		doctype: "Service Estimate",
		fields: ["name", "service_request", "total_amount", "sales_invoice", "status", "modified"],
		columns: [
			{ key: "name", label: "ID", width: "10rem" },
			{ key: "service_request", label: "Service Request", width: "14rem" },
			{ key: "total_amount", label: "Total", width: "10rem" },
			{ key: "sales_invoice", label: "Invoice", width: "12rem" },
			{ key: "status", label: "Status", width: "10rem" },
		],
		statusField: "status",
		formFields: [
			{ section: "Links",  fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
			{ section: "Billing",  fieldname: "labour_amount", label: "Labour", fieldtype: "Float" },
			{ section: "Billing",  fieldname: "travel_amount", label: "Travel", fieldtype: "Float" },
			{ section: "Billing",  fieldname: "spare_amount", label: "Spare", fieldtype: "Float" },
			{ section: "Billing",  fieldname: "total_amount", label: "Total", fieldtype: "Float" },
			{ section: "Billing", fieldname: "sales_invoice", label: "Sales Invoice", fieldtype: "Link", options: "Sales Invoice" },
			{ section: "Notes",  fieldname: "notes", label: "Notes", fieldtype: "Text", col: "sm:col-span-2" },
			{ section: "Status",  fieldname: "status", label: "Status", fieldtype: "Select", options: ["Draft", "Approved", "Invoiced", "Rejected"] },
		],
		createFields: [
			{ section: "Links",  fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
			{ section: "Billing",  fieldname: "labour_amount", label: "Labour", fieldtype: "Float", default: 0 },
			{ section: "Billing",  fieldname: "travel_amount", label: "Travel", fieldtype: "Float", default: 0 },
			{ section: "Billing",  fieldname: "spare_amount", label: "Spare", fieldtype: "Float", default: 0 },
		],
		createMethod: "swiftservice.api.create_service_estimate",
		quickFilters: [{ fieldname: "status", label: "Status", type: "Data" }],
		process: "estimate",
	},
	"engineer-profiles": {
		route: "engineer-profiles",
		listName: "Engineers",
		detailName: "Engineer Detail",
		title: "Engineer Profiles",
		singular: "Engineer Profile",
		doctype: "Engineer Profile",
		fields: ["name", "engineer", "full_name", "region", "status", "workload", "modified"],
		columns: [
			{ key: "engineer", label: "Engineer", width: "14rem" },
			{ key: "full_name", label: "Name", width: "14rem" },
			{ key: "region", label: "Region", width: "10rem" },
			{ key: "workload", label: "Workload", width: "8rem" },
			{ key: "status", label: "Status", width: "10rem" },
		],
		formFields: [
			{ section: "Assignment", fieldname: "engineer", label: "User", fieldtype: "Link", options: "User", reqd: 1 },
			{ section: "Profile", fieldname: "employee", label: "Employee", fieldtype: "Link", options: "Employee" },
			{ section: "Profile", fieldname: "full_name", label: "Full Name", fieldtype: "Data" },
			{ section: "Profile", fieldname: "region", label: "Territory", fieldtype: "Link", options: "Territory" },
			{ section: "Profile", fieldname: "city", label: "City", fieldtype: "Data" },
			{ section: "Profile", fieldname: "skills", label: "Skills", fieldtype: "Text" },
			{ section: "Profile", fieldname: "certifications", label: "Certifications", fieldtype: "Text" },
			{ section: "Profile", fieldname: "product_expertise", label: "Product Expertise", fieldtype: "Text" },
			{ section: "Profile", fieldname: "current_location", label: "Location", fieldtype: "Data" },
			{ section: "Workload", fieldname: "workload", label: "Open Tickets", fieldtype: "Int" },
			{ section: "Workload", fieldname: "max_open_jobs", label: "Max Open Jobs", fieldtype: "Int" },
			{ section: "Status", fieldname: "status", label: "Status", fieldtype: "Select", options: ["Active", "On Leave", "Inactive"] },
		],
		createFields: [
			{ section: "Assignment", fieldname: "engineer", label: "User", fieldtype: "Link", options: "User", reqd: 1 },
			{ section: "Profile", fieldname: "employee", label: "Employee", fieldtype: "Link", options: "Employee" },
			{ section: "Profile", fieldname: "full_name", label: "Full Name", fieldtype: "Data" },
			{ section: "Profile", fieldname: "region", label: "Territory", fieldtype: "Link", options: "Territory" },
			{ section: "Profile", fieldname: "skills", label: "Skills", fieldtype: "Text" },
		],
		quickFilters: [
			{ fieldname: "region", label: "Territory", type: "Link", options: "Territory" },
			{ fieldname: "status", label: "Status", type: "Select", options: ["Active", "On Leave", "Inactive"].map((s) => ({ label: s, value: s })) },
		],
	},
	"van-inventory": {
		route: "van-inventory",
		listName: "Van Inventory",
		detailName: "Van Inventory Detail",
		title: "Van Inventory",
		singular: "Van Stock",
		doctype: "Van Inventory",
		fields: ["name", "engineer", "item_code", "qty", "warehouse", "status", "modified"],
		columns: [
			{ key: "name", label: "ID", width: "10rem" },
			{ key: "engineer", label: "Engineer", width: "14rem" },
			{ key: "item_code", label: "Item", width: "12rem" },
			{ key: "qty", label: "Qty", width: "6rem" },
			{ key: "status", label: "Status", width: "10rem" },
		],
		formFields: [
			{ section: "Assignment",  fieldname: "engineer", label: "Engineer", fieldtype: "Link", options: "User", reqd: 1 },
			{ section: "Product",  fieldname: "item_code", label: "Item", fieldtype: "Link", options: "Item", reqd: 1 },
			{ section: "Stock",  fieldname: "qty", label: "Qty", fieldtype: "Float" },
			{ section: "Stock",  fieldname: "warehouse", label: "Warehouse", fieldtype: "Link", options: "Warehouse" },
			{ section: "Status",  fieldname: "status", label: "Status", fieldtype: "Select", options: ["In Van", "Issued", "Returned"] },
		],
		createFields: [
			{ section: "Assignment",  fieldname: "engineer", label: "Engineer", fieldtype: "Link", options: "User", reqd: 1 },
			{ section: "Product",  fieldname: "item_code", label: "Item", fieldtype: "Link", options: "Item", reqd: 1 },
			{ section: "Stock",  fieldname: "qty", label: "Qty", fieldtype: "Float", default: 1 },
		],
		quickFilters: [{ fieldname: "engineer", label: "Engineer", type: "Data" }],
	},
	"knowledge-base": {
		route: "knowledge-base",
		listName: "Knowledge Base",
		detailName: "KB Article Detail",
		title: "Knowledge Base",
		singular: "Article",
		doctype: "Knowledge Base Article",
		fields: ["name", "title", "category", "item_code", "status", "modified"],
		columns: [
			{ key: "name", label: "ID", width: "8rem" },
			{ key: "title", label: "Title", width: "18rem" },
			{ key: "category", label: "Category", width: "10rem" },
			{ key: "item_code", label: "Item", width: "12rem" },
			{ key: "status", label: "Status", width: "10rem" },
		],
		formFields: [
			{ section: "Article",  fieldname: "title", label: "Title", fieldtype: "Data", reqd: 1, col: "sm:col-span-2" },
			{ section: "Article",  fieldname: "category", label: "Category", fieldtype: "Select", options: ["Hardware", "Software", "Spare", "Calibration", "Installation", "Other"] },
			{ section: "Product",  fieldname: "item_code", label: "Item", fieldtype: "Link", options: "Item" },
			{ section: "Article",  fieldname: "symptoms", label: "Symptoms", fieldtype: "Text", col: "sm:col-span-2 lg:col-span-3" },
			{ section: "Article",  fieldname: "resolution", label: "Resolution", fieldtype: "Text", col: "sm:col-span-2 lg:col-span-3" },
			{ section: "Status",  fieldname: "status", label: "Status", fieldtype: "Select", options: ["Draft", "Published"] },
		],
		createFields: [
			{ section: "Article",  fieldname: "title", label: "Title", fieldtype: "Data", reqd: 1, col: "sm:col-span-2" },
			{ section: "Article",  fieldname: "category", label: "Category", fieldtype: "Select", options: [{ label: "Hardware", value: "Hardware" }, { label: "Software", value: "Software" }, { label: "Spare", value: "Spare" }] },
			{ section: "Article",  fieldname: "symptoms", label: "Symptoms", fieldtype: "Text", col: "sm:col-span-2" },
		],
		quickFilters: [{ fieldname: "category", label: "Category", type: "Data" }],
	},
	"repair-orders": {
		route: "repair-orders",
		listName: "Repair Orders",
		detailName: "Repair Order Detail",
		title: "Repair Orders",
		singular: "Repair Order",
		doctype: "Repair Order",
		fields: [
			"name",
			"service_request",
			"repair_type",
			"priority",
			"serial_no",
			"status",
			"workshop_technician",
			"modified",
		],
		columns: [
			{ key: "name", label: "RO", width: "10rem" },
			{ key: "service_request", label: "Service Request", width: "12rem" },
			{ key: "repair_type", label: "Type", width: "9rem" },
			{ key: "serial_no", label: "Serial", width: "10rem" },
			{ key: "priority", label: "Priority", width: "7rem" },
			{ key: "status", label: "Status", width: "11rem" },
		],
		statusField: "status",
		statusOptions: [
			"Draft",
			"Awaiting Pickup",
			"Picked Up",
			"Received at Workshop",
			"Initial Inspection",
			"Estimate Pending",
			"Customer Approval",
			"Repair In Progress",
			"Waiting Spare",
			"Repair Completed",
			"Testing",
			"Quality Inspection",
			"Ready for Dispatch",
			"Dispatched",
			"Installed",
			"Closed",
			"Cancelled",
			"Not Repairable",
			"Replacement Recommended",
		],
		formFields: [
			{ section: "Basic", fieldname: "naming_series", label: "Series", fieldtype: "Select", options: ["RO-.YYYY.-.#####"], default: "RO-.YYYY.-.#####" },
			{ section: "Basic", fieldname: "company", label: "Company", fieldtype: "Link", options: "Company" },
			{ section: "Basic", fieldname: "branch", label: "Branch", fieldtype: "Data" },
			{ section: "Basic", fieldname: "status", label: "Status", fieldtype: "Select", options: ["Draft", "Awaiting Pickup", "Picked Up", "Received at Workshop", "Initial Inspection", "Estimate Pending", "Customer Approval", "Repair In Progress", "Waiting Spare", "Repair Completed", "Testing", "Quality Inspection", "Ready for Dispatch", "Dispatched", "Installed", "Closed", "Cancelled", "Not Repairable", "Replacement Recommended"] },
			{ section: "Basic", fieldname: "repair_type", label: "Repair Type", fieldtype: "Select", options: ["Warranty", "Chargeable", "AMC", "Internal", "Vendor Repair", "Calibration", "Refurbishment"] },
			{ section: "Basic", fieldname: "priority", label: "Priority", fieldtype: "Select", options: ["Low", "Medium", "High", "Urgent"] },
			{ section: "References", fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
			{ section: "References", fieldname: "engineer_visit", label: "Service Visit", fieldtype: "Link", options: "Engineer Visit" },
			{ section: "References", fieldname: "diagnosis", label: "Diagnosis", fieldtype: "Link", options: "Failure Analysis" },
			{ section: "References", fieldname: "customer", label: "Customer", fieldtype: "Link", options: "Customer" },
			{ section: "References", fieldname: "installed_base", label: "Installed Product", fieldtype: "Link", options: "Installed Base" },
			{ section: "References", fieldname: "serial_no", label: "Serial Number", fieldtype: "Link", options: "Serial No" },
			{ section: "References", fieldname: "amc_contract", label: "AMC Contract", fieldtype: "Link", options: "AMC Contract" },
			{ section: "References", fieldname: "warranty_status", label: "Warranty Status", fieldtype: "Data" },
			{ section: "Product", fieldname: "item_code", label: "Item", fieldtype: "Link", options: "Item" },
			{ section: "Product", fieldname: "item_name", label: "Item Name", fieldtype: "Data", read_only: 1 },
			{ section: "Product", fieldname: "model_no", label: "Model", fieldtype: "Data" },
			{ section: "Product", fieldname: "variant", label: "Variant", fieldtype: "Data" },
			{ section: "Product", fieldname: "revision", label: "Revision", fieldtype: "Data" },
			{ section: "Product", fieldname: "batch_no", label: "Batch", fieldtype: "Link", options: "Batch" },
			{ section: "Logistics", fieldname: "pickup_required", label: "Pickup Required", fieldtype: "Check" },
			{ section: "Logistics", fieldname: "pickup_date", label: "Pickup Date", fieldtype: "Date" },
			{ section: "Logistics", fieldname: "courier", label: "Courier", fieldtype: "Data" },
			{ section: "Logistics", fieldname: "tracking_number", label: "Tracking Number", fieldtype: "Data" },
			{ section: "Logistics", fieldname: "received_date", label: "Received Date", fieldtype: "Datetime" },
			{ section: "Logistics", fieldname: "dispatch_date", label: "Dispatch Date", fieldtype: "Datetime" },
			{ section: "Logistics", fieldname: "delivery_date", label: "Delivery Date", fieldtype: "Date" },
			{ section: "Workshop Receipt", fieldname: "received_by", label: "Received By", fieldtype: "Link", options: "User" },
			{ section: "Workshop Receipt", fieldname: "packaging_condition", label: "Packaging", fieldtype: "Select", options: ["", "Good", "Damaged", "Opened"] },
			{ section: "Workshop Receipt", fieldname: "seal_condition", label: "Seal", fieldtype: "Select", options: ["", "Intact", "Broken", "Missing"] },
			{ section: "Workshop Receipt", fieldname: "accessories_received", label: "Accessories", fieldtype: "Small Text", col: "sm:col-span-2 xl:col-span-3" },
			{ section: "Workshop Receipt", fieldname: "physical_damage", label: "Physical Damage", fieldtype: "Check" },
			{ section: "Workshop Receipt", fieldname: "receipt_remarks", label: "Remarks", fieldtype: "Small Text", col: "sm:col-span-2 xl:col-span-3" },
			{ section: "Inspection", fieldname: "visual_inspection", label: "Visual", fieldtype: "Small Text", col: "sm:col-span-2 xl:col-span-3" },
			{ section: "Inspection", fieldname: "functional_inspection", label: "Functional", fieldtype: "Small Text", col: "sm:col-span-2 xl:col-span-3" },
			{ section: "Inspection", fieldname: "power_on_test", label: "Power-on Test", fieldtype: "Select", options: ["", "Pass", "Fail", "Not Done"] },
			{ section: "Inspection", fieldname: "missing_accessories", label: "Missing Accessories", fieldtype: "Small Text", col: "sm:col-span-2 xl:col-span-3" },
			{ section: "Inspection", fieldname: "damage_assessment", label: "Damage Assessment", fieldtype: "Small Text", col: "sm:col-span-2 xl:col-span-3" },
			{ section: "Diagnosis", fieldname: "failure_category", label: "Failure Category", fieldtype: "Data" },
			{ section: "Diagnosis", fieldname: "root_cause", label: "Root Cause", fieldtype: "Small Text", col: "sm:col-span-2 xl:col-span-3" },
			{ section: "Diagnosis", fieldname: "repair_complexity", label: "Complexity", fieldtype: "Select", options: ["", "Low", "Medium", "High", "Critical"] },
			{ section: "Diagnosis", fieldname: "estimated_repair_time", label: "Est. Hours", fieldtype: "Float" },
			{ section: "Diagnosis", fieldname: "estimated_cost", label: "Est. Cost", fieldtype: "Currency" },
			{ section: "Diagnosis", fieldname: "not_repairable", label: "Not Repairable", fieldtype: "Check" },
			{ section: "Diagnosis", fieldname: "ber_flag", label: "BER", fieldtype: "Check" },
			{ section: "Estimate", fieldname: "labour_cost", label: "Labour Cost", fieldtype: "Currency" },
			{ section: "Estimate", fieldname: "spare_cost", label: "Spare Cost", fieldtype: "Currency" },
			{ section: "Estimate", fieldname: "courier_cost", label: "Courier Cost", fieldtype: "Currency" },
			{ section: "Estimate", fieldname: "misc_cost", label: "Misc Cost", fieldtype: "Currency" },
			{ section: "Estimate", fieldname: "tax_amount", label: "Tax", fieldtype: "Currency" },
			{ section: "Estimate", fieldname: "total_estimate", label: "Total Estimate", fieldtype: "Currency", read_only: 1 },
			{ section: "Estimate", fieldname: "customer_approval", label: "Customer Approval", fieldtype: "Select", options: ["Pending", "Approved", "Rejected", "Revised", "Not Required"] },
			{ section: "Assignment", fieldname: "workshop_technician", label: "Technician", fieldtype: "Link", options: "User" },
			{ section: "Assignment", fieldname: "supervisor", label: "Supervisor", fieldtype: "Link", options: "User" },
			{ section: "Assignment", fieldname: "department", label: "Department", fieldtype: "Data" },
			{ section: "Assignment", fieldname: "planned_start", label: "Planned Start", fieldtype: "Datetime" },
			{ section: "Assignment", fieldname: "planned_completion", label: "Planned Completion", fieldtype: "Datetime" },
			{ section: "Vendor", fieldname: "vendor", label: "Vendor", fieldtype: "Link", options: "Supplier" },
			{ section: "Vendor", fieldname: "vendor_sent_date", label: "Sent Date", fieldtype: "Date" },
			{ section: "Vendor", fieldname: "vendor_expected_date", label: "Expected Date", fieldtype: "Date" },
			{ section: "Vendor", fieldname: "vendor_returned_date", label: "Returned Date", fieldtype: "Date" },
			{ section: "Vendor", fieldname: "vendor_cost", label: "Vendor Cost", fieldtype: "Currency" },
			{ section: "Vendor", fieldname: "vendor_warranty", label: "Vendor Warranty", fieldtype: "Data" },
			{ section: "Quality", fieldname: "qi_inspector", label: "Inspector", fieldtype: "Link", options: "User" },
			{ section: "Quality", fieldname: "qi_date", label: "QI Date", fieldtype: "Datetime" },
			{ section: "Quality", fieldname: "qi_result", label: "QI Result", fieldtype: "Select", options: ["", "Pass", "Fail", "Rework"] },
			{ section: "Quality", fieldname: "qi_ncr", label: "NCR", fieldtype: "Data" },
			{ section: "Quality", fieldname: "qi_rework_required", label: "Rework Required", fieldtype: "Check" },
			{ section: "Dispatch", fieldname: "dispatch_courier", label: "Courier", fieldtype: "Data" },
			{ section: "Dispatch", fieldname: "dispatch_tracking", label: "Tracking", fieldtype: "Data" },
			{ section: "Dispatch", fieldname: "packaging_type", label: "Packaging Type", fieldtype: "Data" },
			{ section: "Dispatch", fieldname: "dispatched_by", label: "Dispatch By", fieldtype: "Link", options: "User" },
			{ section: "Dispatch", fieldname: "installation_required", label: "Installation Required", fieldtype: "Check" },
			{ section: "Dispatch", fieldname: "installation_visit", label: "Installation Visit", fieldtype: "Link", options: "Engineer Visit" },
			{ section: "Completion", fieldname: "work_done", label: "Work Done", fieldtype: "Text", col: "sm:col-span-2 xl:col-span-3" },
			{ section: "Completion", fieldname: "parts_replaced", label: "Parts Replaced", fieldtype: "Small Text", col: "sm:col-span-2 xl:col-span-3" },
			{ section: "Completion", fieldname: "firmware_updated", label: "Firmware Updated", fieldtype: "Check" },
			{ section: "Completion", fieldname: "software_updated", label: "Software Updated", fieldtype: "Check" },
			{ section: "Completion", fieldname: "final_condition", label: "Final Condition", fieldtype: "Select", options: ["", "Good", "Fair", "Refurbished"] },
			{ section: "Completion", fieldname: "warranty_extension_days", label: "Warranty Extension Days", fieldtype: "Int" },
		],
		createFields: [
			{ section: "References", fieldname: "service_request", label: "Service Request", fieldtype: "Link", options: "Swift Service Request", reqd: 1 },
			{ section: "Basic", fieldname: "repair_type", label: "Repair Type", fieldtype: "Select", options: ["Warranty", "Chargeable", "AMC", "Internal", "Vendor Repair"], default: "Warranty" },
			{ section: "Basic", fieldname: "priority", label: "Priority", fieldtype: "Select", options: ["Low", "Medium", "High", "Urgent"], default: "Medium" },
			{ section: "Basic", fieldname: "naming_series", label: "Series", fieldtype: "Select", options: ["RO-.YYYY.-.#####"], default: "RO-.YYYY.-.#####" },
		],
		createMethod: "swiftservice.api.create_repair_order",
		quickFilters: [
			{ fieldname: "status", label: "Status", type: "Select", options: ["Repair In Progress", "Waiting Spare", "Testing", "Quality Inspection", "Ready for Dispatch"].map((s) => ({ label: s, value: s })) },
			{ fieldname: "repair_type", label: "Type", type: "Select", options: ["Warranty", "Chargeable", "AMC"].map((s) => ({ label: s, value: s })) },
		],
		process: "repair",
		submittable: true,
	},
};

export function getResourceByRoute(routeKey) {
	return resources[routeKey];
}

export function getResourceByDoctype(doctype) {
	return Object.values(resources).find((r) => r.doctype === doctype);
}
